<?php

namespace dev\components;

use yii\base\Component;
use yii\caching\FileCache;

class DCache extends FileCache
{
    public $mark = '';

    /**
     * @return string
     * @param $key string
     * */
    public function setKey($key)
    {
        return $this->mark . $key;
    }

    public function add($key, $value, $duration = 0, $dependency = null)
    {
        return parent::add($this->mark . $key, $value, $duration, $dependency); // TODO: Change the autogenerated stub
    }

    public function delete($key)
    {
        return parent::delete($this->mark . $key); // TODO: Change the autogenerated stub
    }

    public function get($key)
    {
        //echo $this->mark;
        //print_r($_SERVER['HTTP_HOST']);
        return parent::get($this->mark . $key); // TODO: Change the autogenerated stub
    }

    public function set($key, $value, $duration = null, $dependency = null)
    {
        return parent::set($this->mark . $key, $value, $duration, $dependency); // TODO: Change the autogenerated stub
    }


}